"use client";

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useCrowdStore } from '@/context/CrowdStore';
import { BottomNav, CommunityReportCard, CrowdBadge, Icon, JourneyTimeline, PrimaryButton, RecommendationCard, RouteCard, SecondaryButton } from './ui';

const routes = [
  { mode: 'Metro + Shuttle', time: '52 min', crowd: 'Low' as const, comfort: 82, seat: 74, cost: '₹42', recommended: true },
  { mode: 'KSRTC Bus', time: '46 min', crowd: 'High' as const, comfort: 48, seat: 25, cost: '₹31' },
  { mode: 'Train + Bus', time: '58 min', crowd: 'Moderate' as const, comfort: 67, seat: 52, cost: '₹36' },
];
const Back = ({ href }: { href: string }) => <Link href={href} className="mb-6 inline-block rounded-xl p-1"><Icon>arrow_back</Icon></Link>;

export function PlannerScreen() { const [destination, setDestination] = useState(''); return <main className="app-shell"><div className="page"><header className="mb-9 flex items-center justify-between">
  <div className="flex items-center gap-2">
    <div className="grid h-8 w-8 place-items-center rounded-lg bg-blue-50 text-brand"><Icon>route</Icon></div>
    <span className="text-base font-extrabold tracking-tight">Ride or Wait</span></div>
    <button className="rounded-xl bg-surface p-2.5"><Icon className="text-xl">notifications</Icon></button></header>
    <h1 className="text-[28px] font-extrabold tracking-tight">Plan your trip</h1>
    <p className="mt-1 text-sm text-muted">Choose a route that feels right today.</p>
    <div className="mt-7 space-y-3"><div className="field"><Icon className="text-brand">my_location</Icon><span><span className="label mb-1 block">From</span>Current Location</span></div>
    <div className="ml-6 h-2 border-l-2 border-dashed border-slate-200"/>
    <label className="field cursor-text"><Icon className="text-sky">location_on</Icon><span className="flex-1">
      <span className="label mb-1 block">To</span><input aria-label="Search destination" value={destination} onChange={(event) => setDestination(event.target.value)} placeholder="Search Destination" className="w-full bg-transparent text-sm font-medium text-ink outline-none placeholder:text-muted" /></span>
      <Icon className="text-muted">search</Icon></label></div>
    <section className="mt-7"><span className="label">Travel preference</span>
    <div className="mt-3 grid grid-cols-2 gap-2">{['Fastest','Cheapest','Comfortable','Least Walking'].map(item => <button key={item} className={`rounded-xl border px-3 py-3 text-xs font-semibold ${item === 'Comfortable' ? 'border-brand bg-blue-50 text-brand' : 'border-line text-muted'}`}>{item}</button>)}</div></section><div className="mt-7"><PrimaryButton href="/recommendation">Find Best Route</PrimaryButton></div><section className="mt-10"><h2 className="text-base font-bold">Recent searches</h2><div className="mt-3 divide-y divide-line">{['Vyttila → Kakkanad','Aluva → Edappally'].map(item => <Link href="/recommendation" key={item} className="flex items-center gap-3 py-4 text-sm font-medium"><Icon className="text-muted">history</Icon>{item}<Icon className="ml-auto text-muted">chevron_right</Icon></Link>)}</div></section></div><BottomNav active="journey"/></main>; }

export function RecommendationScreen() { const { crowdByRouteId } = useCrowdStore(); const metroCrowd = crowdByRouteId['metro-vyttila-kakkanad']; return <main className="app-shell"><div className="page"><Back href="/"/><span className="label">Your recommendation</span><h1 className="mt-1 text-[27px] font-extrabold tracking-tight">Ride now, comfortably.</h1><div className="mt-5"><RecommendationCard crowdLevel={metroCrowd}/></div><div className="mt-6 rounded-2xl bg-surface p-4"><div className="flex gap-3"><Icon className="text-brand">auto_awesome</Icon><p className="text-sm leading-6 text-ink">Take Metro. Although it takes 6 minutes longer than the bus, it offers significantly better comfort and a higher chance of a seat.</p></div><p className="mt-3 pl-7 text-xs font-semibold text-muted">92% confident</p></div><div className="mt-7 space-y-3"><PrimaryButton href="/journey">Start Journey</PrimaryButton><SecondaryButton href="/compare">Compare Routes</SecondaryButton></div></div><BottomNav active="journey"/></main>; }

export function CompareScreen() { const { crowdByRouteId } = useCrowdStore(); const routeIds = ['metro-vyttila-kakkanad', 'ksrtc-vyttila-kakkanad', 'train-vyttila-kakkanad']; const toBadgeLevel = (level: 'low' | 'moderate' | 'high') => level === 'low' ? 'Low' as const : level === 'moderate' ? 'Moderate' as const : 'High' as const; const liveRoutes = routes.map((route, index) => ({ ...route, crowd: toBadgeLevel(crowdByRouteId[routeIds[index]] ?? route.crowd.toLowerCase() as 'low' | 'moderate' | 'high') })); return <main className="app-shell"><div className="page"><Back href="/recommendation"/><span className="label">Vyttila to Kakkanad</span><h1 className="mt-1 text-[27px] font-extrabold tracking-tight">Compare routes</h1><p className="mt-1 text-sm text-muted">Placeholder estimates based on recent reports.</p><div className="mt-6 space-y-3">{liveRoutes.map(route => <RouteCard key={route.mode} route={route}/>)}</div></div><BottomNav active="journey"/></main>; }

export function JourneyScreen() { const [showAdvice, setShowAdvice] = useState(false); useEffect(() => { const timer = window.setTimeout(() => setShowAdvice(true), 5000); return () => window.clearTimeout(timer); }, []); return <main className="app-shell"><div className="page"><div className="flex items-center justify-between"><div><span className="label">Active journey</span><h1 className="mt-1 text-[25px] font-extrabold">To Kakkanad</h1></div><CrowdBadge level="Low"/></div><div className="mt-5 grid h-40 place-items-center rounded-2xl bg-[#EAF2FF] text-center"><div><Icon className="text-4xl text-brand">map</Icon><p className="mt-2 text-xs font-semibold text-brand">Map placeholder</p></div></div><JourneyTimeline/>{showAdvice && <div className="animate-[fade-in_.45s_ease-out] rounded-2xl border border-blue-100 bg-blue-50 p-4"><div className="flex gap-3"><Icon className="text-brand">tips_and_updates</Icon><div><h3 className="text-sm font-bold">AI advice</h3><p className="mt-1 text-sm leading-5 text-slate-600">The next feeder bus is crowded. Stay on Metro until Aluva.</p></div></div></div>}<div className="mt-6"><PrimaryButton href="/">Finish Journey</PrimaryButton></div></div><BottomNav active="trips"/></main>; }

export function CommunityScreen() { const [selected, setSelected] = useState<'low' | 'moderate' | 'high' | null>(null); const [submitted, setSubmitted] = useState(false); const { reports, setCrowdLevel } = useCrowdStore(); const options: Array<[string, string, 'low' | 'moderate' | 'high']> = [['🟢','Plenty of Seats','low'],['🟡','Moderate','moderate'],['🟠','Standing','high'],['🔴','Fully Packed','high']]; const submit = () => { if (!selected) return; setCrowdLevel('metro-vyttila-kakkanad', selected, 'Metro'); setSubmitted(true); }; const displayLevel = (level: 'low' | 'moderate' | 'high'): 'Low' | 'Moderate' | 'High' => level === 'low' ? 'Low' : level === 'moderate' ? 'Moderate' : 'High'; return <main className="app-shell"><div className="page"><span className="label">Community</span><h1 className="mt-1 text-[27px] font-extrabold tracking-tight">Help other commuters</h1><p className="mt-2 text-sm text-muted">How crowded is your ride?</p><div className="mt-6 grid grid-cols-2 gap-3">{options.map(([emoji, text, level]) => <button onClick={() => { setSelected(level); setSubmitted(false); }} key={text} className={`rounded-2xl border p-4 text-left ${selected === level ? 'border-brand bg-blue-50' : 'border-line'}`}><div className="text-xl">{emoji}</div><div className="mt-2 text-sm font-bold">{text}</div></button>)}</div><div className="mt-4"><button onClick={submit} disabled={!selected} className="w-full rounded-2xl bg-brand px-5 py-4 text-sm font-bold text-white shadow-[0_5px_12px_rgba(37,99,235,.22)] disabled:cursor-not-allowed disabled:opacity-40">{submitted ? 'Report submitted' : 'Submit report'}</button></div><section className="mt-9"><h2 className="text-base font-bold">Latest community reports</h2><div className="mt-3 space-y-2">{reports.map(report => <CommunityReportCard key={report.id} mode={report.mode} crowd={displayLevel(report.crowd)} time={report.timestamp}/>)}</div></section></div><BottomNav active="community"/></main>; }

export function ProfileScreen() { const items = [['bookmark','Saved routes'],['commute','Trips'],['groups','Community contributions'],['settings','Settings'],['dark_mode','Dark Mode — Coming Soon'],['info','About'],['privacy_tip','Privacy']]; return <main className="app-shell"><div className="page"><span className="label">Account</span><div className="mt-3 flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-full bg-blue-50 text-lg font-bold text-brand">AK</div><div><h1 className="text-xl font-extrabold">Akbar</h1><p className="text-sm text-muted">Comfortable travel</p></div></div><div className="mt-8 space-y-2">{items.map(([icon, label]) => <button disabled={label.includes('Coming')} key={label} className="flex w-full items-center gap-3 rounded-xl px-3 py-3.5 text-left text-sm font-medium disabled:text-slate-300"><Icon className="text-muted">{icon}</Icon>{label}<Icon className="ml-auto text-muted">chevron_right</Icon></button>)}</div></div><BottomNav active="profile"/></main>; }
