import Link from 'next/link';
import { ReactNode } from 'react';

export const Icon = ({ children, className = '' }: { children: string; className?: string }) => <span className={`icon ${className}`}>{children}</span>;
export const PrimaryButton = ({ children, href, className = '' }: { children: ReactNode; href?: string; className?: string }) => href ? <Link href={href} className={`block w-full rounded-2xl bg-brand px-5 py-4 text-center text-sm font-bold text-white shadow-[0_5px_12px_rgba(37,99,235,.22)] ${className}`}>{children}</Link> : <button className={`w-full rounded-2xl bg-brand px-5 py-4 text-sm font-bold text-white shadow-[0_5px_12px_rgba(37,99,235,.22)] ${className}`}>{children}</button>;
export const SecondaryButton = ({ children, href }: { children: ReactNode; href?: string }) => href ? <Link href={href} className="block w-full rounded-2xl border border-line bg-white px-5 py-4 text-center text-sm font-bold text-ink">{children}</Link> : <button className="w-full rounded-2xl border border-line bg-white px-5 py-4 text-sm font-bold text-ink">{children}</button>;
export const CrowdBadge = ({ level }: { level: 'Low' | 'Moderate' | 'High' | 'Packed' }) => { const style = { Low: 'bg-green-50 text-green-700', Moderate: 'bg-amber-50 text-amber-700', High: 'bg-orange-50 text-orange-700', Packed: 'bg-red-50 text-red-700' }[level]; const dot = { Low: '🟢', Moderate: '🟡', High: '🔴', Packed: '🔴' }[level]; return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[11px] font-bold ${style}`}>{dot} {level}</span>; };
export const ComfortProgress = ({ value }: { value: number }) => <div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-brand" style={{ width: `${value}%` }} /></div>;
export function BottomNav({ active }: { active: 'journey' | 'community' | 'trips' | 'profile' }) { const tabs = [['/','route','Journey','journey'],['/community','groups','Community','community'],['/journey','format_list_bulleted','Trips','trips'],['/profile','person','Profile','profile']] as const; return <nav className="fixed bottom-0 left-1/2 z-20 flex w-full max-w-[420px] -translate-x-1/2 border-t border-line bg-white px-3 pb-[max(12px,env(safe-area-inset-bottom))] pt-2">{tabs.map(([href, icon, label, key]) => <Link key={key} href={href} className={`flex flex-1 flex-col items-center gap-1 rounded-xl py-1.5 text-[10px] font-semibold ${active === key ? 'text-brand' : 'text-muted'}`}><Icon className="text-[22px]">{icon}</Icon>{label}</Link>)}</nav>; }
export function RecommendationCard({ crowdLevel = "low" }: { crowdLevel?: "low" | "moderate" | "high" }) { const crowdCopy = { low: "🟢 Low crowd", moderate: "🟡 Moderate crowd", high: "🔴 High crowd" }[crowdLevel]; return <div className="overflow-hidden rounded-2xl bg-gradient-to-br from-brand to-sky p-5 text-white shadow-[0_8px_22px_rgba(37,99,235,.25)]"><div className="flex items-center justify-between"><span className="rounded-full bg-white/20 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider">Best for comfort</span><Icon>auto_awesome</Icon></div><h2 className="mt-5 text-2xl font-extrabold">Metro + Shuttle</h2><p className="mt-1 text-sm text-blue-100">Vyttila → Kakkanad</p><div className="mt-5 grid grid-cols-3 gap-3 border-t border-white/25 pt-4"><Metric icon="schedule" value="52 min" label="Travel time"/><Metric icon="chair" value="82%" label="Comfort"/><Metric icon="event_seat" value="74%" label="Seat chance"/></div><div className="mt-4 flex items-center justify-between text-xs"><span>₹42 estimated</span><span className="rounded-full bg-white/15 px-2 py-1">{crowdCopy}</span><Icon>wb_sunny</Icon></div></div>; }
function Metric({ icon, value, label }: { icon: string; value: string; label: string }) { return <div><Icon className="text-[18px] text-blue-100">{icon}</Icon><div className="mt-1 text-sm font-bold">{value}</div><div className="text-[10px] text-blue-100">{label}</div></div>; }
export type RouteInfo = { mode: string; time: string; crowd: 'Low' | 'Moderate' | 'High' | 'Packed'; comfort: number; seat: number; cost: string; recommended?: boolean };
export function RouteCard({ route }: { route: RouteInfo }) { return <div className="card"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><h3 className="font-bold">{route.mode}</h3>{route.recommended && <span className="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2 py-1 text-[10px] font-bold text-brand"><Icon className="text-sm">auto_awesome</Icon>AI Recommended</span>}</div><p className="mt-1 text-sm text-muted">{route.time} · {route.cost}</p></div><CrowdBadge level={route.crowd}/></div><div className="mt-4 grid grid-cols-2 gap-5 text-xs"><div><div className="mb-1 flex justify-between text-muted"><span>Comfort</span><b className="text-ink">{route.comfort}%</b></div><ComfortProgress value={route.comfort}/></div><div><div className="mb-1 flex justify-between text-muted"><span>Seat chance</span><b className="text-ink">{route.seat}%</b></div><ComfortProgress value={route.seat}/></div></div></div>; }
export function JourneyTimeline() { const stops = [['subway','Board Metro','Vyttila Metro Station','Now'],['train','Edappally','Stay onboard','18 min'],['subway','Aluva','Change to shuttle','36 min'],['directions_bus','Kakkanad','Arrive','52 min']]; return <div className="mt-5">{stops.map(([icon, title, description, time], index) => <div key={title} className="flex min-h-[76px] gap-4"><div className="flex flex-col items-center"><div className={`grid h-9 w-9 place-items-center rounded-full ${index === 0 ? 'bg-blue-50 text-brand' : 'bg-slate-100 text-muted'}`}><Icon className="text-lg">{icon}</Icon></div>{index < stops.length - 1 && <div className="my-1 h-full border-l-2 border-dashed border-line"/>}</div><div className="pt-1"><div className="flex items-center gap-3"><h3 className="text-sm font-bold">{title}</h3><span className="text-xs text-muted">{time}</span></div><p className="mt-1 text-xs text-muted">{description}</p></div></div>)}</div>; }
export function CommunityReportCard({ mode, crowd, time }: { mode: string; crowd: 'Low' | 'Moderate' | 'High' | 'Packed'; time: string }) { return <div className="card flex items-center justify-between py-3"><div><div className="text-sm font-bold">{mode}</div><div className="mt-1 text-xs text-muted">{time}</div></div><CrowdBadge level={crowd}/></div>; }
